# Generated by Django 2.1.7 on 2019-04-03 14:01

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='country',
            field=django_countries.fields.CountryField(default='NZ', max_length=2),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='phone'),
        ),
    ]
