# Generated by Django 2.1.7 on 2019-04-03 14:06

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20190403_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
