# Generated by Django 2.1.7 on 2019-04-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20190403_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_review',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='rating'),
        ),
    ]
