# Generated by Django 2.1.7 on 2019-04-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_restaurant_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('Meatlovers', 'Meatlovers'), ('Wings', 'Wings'), ('Italian', 'Italian'), ('Chinese', 'Chinese'), ('French', 'French')], max_length=150, verbose_name='category'),
        ),
    ]
