# Generated by Django 2.1.7 on 2019-04-03 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20190403_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant_review',
            name='review_likes',
        ),
        migrations.AddField(
            model_name='reviewlikes',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='my_app.Restaurant_review', verbose_name='review_likes'),
        ),
    ]
