# Generated by Django 2.1.7 on 2019-04-04 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20190403_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments_on_reviews',
            name='comment_likes',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_reviews',
        ),
        migrations.AddField(
            model_name='commentlikes',
            name='comment_like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_comment', to='my_app.Comments_on_reviews', verbose_name='comment_like'),
        ),
        migrations.AddField(
            model_name='restaurant_review',
            name='restaurant_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='my_app.Restaurant', verbose_name='restaurant_review'),
        ),
    ]
