# Generated by Django 2.1.7 on 2019-04-04 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20190404_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='average_rating',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='average_rating'),
        ),
        migrations.AlterField(
            model_name='restaurant_review',
            name='restaurant_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='my_app.Restaurant', verbose_name='restaurant_review'),
        ),
    ]
