# Generated by Django 2.1.7 on 2019-04-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_auto_20190404_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='average_rating',
        ),
    ]
