version: '3'
services:
  database:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - dev.env
    volumes:
      - database:/var/lib/postgresql/data

  app:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-2019-02/group-projects/aries:latest
    restart: always
    env_file:
      - dev.env
    command: '/usr/sbin/sshd -D'
    ports:
      - '8000:8000'
      - '4777:22'
    depends_on:
      - database
    volumes:
      - ./frontend:/frontend
      - ./app:/app
      - ./media-files:/media-files
      - ./static-files:/static-files
      - ./scripts:/scripts

volumes:
  database:
