version: "3"
services:
  frontend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-2019-02/group-projects/aries:master
    volumes:
      - frontend:/frontend-deploy
    command: "bash -c 'rm -rf /frontend-deploy/* && cp -r /frontend/build/* /frontend-deploy'"

  database:
    image: postgres:latest
    restart: always
    env_file:
      - prod.env
    volumes:
      - database:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    volumes:
      - frontend:/frontend
      - static-files:/static-files
      - media-files:/media-files
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    command: /bin/bash -c "nginx -g 'daemon off;'"

  app:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-2019-02/group-projects/aries:master
    restart: always
    env_file:
      - prod.env
    depends_on:
      - database
    command: "sh /scripts/run.sh"
    volumes:
      - static-files:/static-files
      - media-files:/media-files

volumes:
  database:
  frontend:
  static-files:
  media-files:
